const createInitialSkuData = ({ user_id, strictAdherence }) => ({
  sku_name: '',
  composite_type: '',
  client_id: user_id,
  ply: '',
  client: '',
  length: '',
  width: '',
  height: '',
  unit: '',
  joints: '',
  ups: '',
  inner_outer_dimension: '',
  flap_width: '',
  flap_tolerance: '',
  length_trimming_tolerance: 20,
  width_trimming_tolerance: 20,
  width_board_size_cm2: '',
  length_board_size_cm2: '',
  strict_adherence: strictAdherence,
  customer_reference: '',
  reference_number: '',
  internal_id: '',
  board_size_cm2: '',
  deckle_size: '',
  minimum_order_level: '',
  sku_type: 'RSC box',
  part_value: [],
  part_count: '',
  sku_values: [
    {
      layer: '',
      gsm: '',
      bf: '',
      material: '',
      color: '',
      flute_type: '',
    },
  ],
})

export default createInitialSkuData
